from easy_travel.Address.adrcontroller import *
from easy_travel.Vehical.vehicalcontroller import *
from easy_travel.Owner.ownercontroller import *
from easy_travel.Driver.drivercontroller import *
from easy_travel.Customer.custcontroller import *
from easy_travel.History.histcontroller import *
from easy_travel.Trip.trcontroller import *
from easy_travel.Payment.paycontroller import *
from easy_travel.Notification.notcontroller import *